return { -- a table of all items we want to ignore when building
"Base.Key2", "farming.MayonnaiseWaterFull", "farming.RemouladeWaterFull", "SapphCooking.TequilaWaterFull",
"SapphCooking.VodkaWaterFull", "SapphCooking.RumWaterFull", "SapphCooking.FullWaterThermos",
"SapphCooking.WaterColaBottle", "SapphCooking.SakeWaterFull", "SapphCooking.FullWater_FrenchPress",
"SapphCooking.LiqueurWaterFull", "SapphCooking.GinWaterFull", "SapphCooking.CachacaWaterFull", "Base.PlasticCupWater",
"Base.WaterBleachBottle", "Base.BeerWaterFull", "Base.WaterSaucepan", "Base.WaterPaintbucket", "Base.WaterMugSpiffo",
"Base.WaterTeacup", "Base.GlassTumblerWater", "Base.WaterMugRed", "Base.FullKettle", "Base.WaterMug",
"Base.WaterPopBottle", "Base.WaterPot", "Base.WaterBowl", "Base.WaterMugWhite", "Base.WhiskeyWaterFull",
"Base.WineWaterFull", "Base.BucketWaterFull", "farming.WateredCanFull", "SapphCooking.MochiPrep",
"SapphCooking.Blender_Sorbet", "SapphCooking.Blender_Prep_Shake", "Base.Map", "Base.Wound_RHand_Bite_Male",
"Base.Wound_Neck_Bite_Male", "Base.Wound_LHand_Laceration_Female", "Base.Bandage_Abdomen_Blood",
"Base.Bandage_LeftUpperLeg", "Base.Bandage_Chest_Blood", "Base.Bandage_Chest", "Base.Bandage_Head",
"Base.Wound_RUArm_Laceration_Female", "Base.Wound_LUArm_Bite_Female", "Base.Wound_LUArm_Laceration_Male",
"Base.Wound_LHand_Scratch_Male", "Base.Wound_RHand_Scratch_Male", "Base.Wound_Abdomen_Scratch_Female",
"Base.Bandage_RightHand", "Base.Wound_RUArm_Scratch_Female", "Base.Bandage_LeftLowerLeg",
"Base.Wound_Abdomen_Laceration_Male", "Base.Wound_RForearm_Bite_Male", "Base.Wound_RUArm_Laceration_Male",
"Base.Bandage_RightLowerLeg", "Base.Wound_LHand_Laceration_Male", "Base.Bandage_LeftHand_Blood",
"Base.Wound_Neck_Laceration_Female", "Base.Wound_Neck_Laceration_Male", "Base.Bandage_RightFoot_Blood",
"Base.Wound_Chest_Bite_Female", "Base.Wound_LHand_Bite_Male", "Base.Bandage_LeftUpperArm_Blood",
"Base.Wound_Abdomen_Scratch_Male", "Base.Wound_RForearm_Scratch_Female", "Base.Wound_LUArm_Bite_Male",
"Base.Bandage_Neck", "Base.Bandage_RightUpperArm_Blood", "Base.Bandage_Groin", "Base.Bandage_Neck_Blood",
"Base.Wound_Neck_Bite_Female", "Base.Bandage_RightUpperLeg", "Base.Bandage_RightLowerArm_Blood",
"Base.Wound_Groin_Bite_Male", "Base.Wound_Groin_Scratch_Male", "Base.Wound_Abdomen_Bite_Male",
"Base.Wound_LUArm_Scratch_Female", "Base.Wound_RHand_Bite_Female", "Base.Bandage_LeftLowerArm_Blood",
"Base.Wound_LHand_Bite_Female", "Base.Bandage_LeftHand", "Base.Wound_LUArm_Laceration_Female",
"Base.Wound_LUArm_Scratch_Male", "Base.Wound_LForearm_Laceration_Male", "Base.Bandage_LeftUpperArm",
"Base.Bandage_RightLowerLeg_Blood", "Base.Wound_Groin_Bite_Female", "Base.Bandage_LeftLowerLeg_Blood",
"Base.Bandage_Abdomen", "Base.Wound_LForearm_Scratch_Female", "Base.Wound_RHand_Laceration_Male",
"Base.Wound_Chest_Laceration_Female", "Base.Wound_RHand_Laceration_Female", "Base.Wound_RForearm_Bite_Female",
"Base.Wound_Abdomen_Laceration_Female", "Base.Wound_Neck_Scratch_Female", "Base.Wound_RForearm_Laceration_Male",
"Base.Bandage_Head_Blood", "Base.Wound_RForearm_Scratch_Male", "Base.Wound_RUArm_Scratch_Male", "Base.BandageDirty",
"Base.Bandage_LeftFoot_Blood", "Base.Wound_RHand_Scratch_Female", "Base.Wound_Abdomen_Bite_Female",
"Base.Bandage_RightHand_Blood", "Base.Bandage_LeftLowerArm", "Base.Wound_Chest_Laceration_Male",
"Base.Wound_Groin_Laceration_Female", "Base.Bandage_LeftFoot", "Base.Wound_Chest_Bite_Male",
"Base.Wound_Neck_Scratch_Male", "Base.Bandage_LeftUpperLeg_Blood", "Base.Wound_Chest_Scratch_Male",
"Base.Wound_RUArm_Bite_Female", "Base.Wound_RForearm_Laceration_Female", "Base.Bandage_RightUpperLeg_Blood",
"Base.Bandage_RightLowerArm", "Base.Bandage_Groin_Blood", "Base.Wound_RUArm_Bite_Male",
"Base.Wound_LForearm_Laceration_Female", "Base.Bandage_RightFoot", "Base.Bandage_RightUpperArm",
"Base.Wound_LForearm_Bite_Male", "Base.Wound_Groin_Scratch_Female", "Base.Wound_LHand_Scratch_Female",
"Base.Wound_LForearm_Bite_Female", "Base.Wound_Groin_Laceration_Male", "Base.Wound_LForearm_Scratch_Male",
"Base.DenimStripsDirty", "Base.BucketPlasterFull", "Base.TreeBranch", "Base.IronIngot", "Base.LogStacks4",
"Base.LogStacks3", "Base.LogStacks2", "Base.UnusableWood", "Base.Log", "Base.LogStacks2", "Base.BucketConcreteFull",
"Base.SharpedStone", "Base.Drawer", "Base.DishClothWet", "Base.RippedSheetsDirty", "Base.BathTowelWet",
"Base.FertilizerEmpty", "Base.CompostBag", "Base.PetrolBleachBottle", "Base.PetrolPopBottle", "Base.WhiskeyPetrol",
"Base.EmptyPetrolCan", "Base.WaterBottlePetrol", "Base.WhiskeyPetrol", "Base.Wound_Chest_Scratch_Female",
"Base.WinePetrol", "Base.LeatherStripsDirty", "Base.PaintbucketEmpty", "Base.TinCanEmpty", "Base.Flint",
"Base.TinCanEmpty", "Base.BareHands"}
