#version 330

// PhunMart vending machine shader, no-power-needed look. Generated from one template with its two
// siblings; only the LOOK block differs:
//     phunmartVending      needs power and has it: the glow mask shows at full brightness
//     phunmartVendingSoft  needs no power: the glow mask at reduced brightness
//     phunmartVendingOff   needs power and has none: no glow, masked areas dimmed and greyed
// The base is vanilla door.frag. The vertex shaders are unmodified vanilla basicEffect copies.
// Generated by Tools/shaders/make_vending_shaders.js from vending.frag.tpl: edit those, not this.
//
// The texture follows Tools/blender/vending_layout.py: the colour layout fills the image except
// the bottom-right quarter, which holds the whole image again at half size as the glow mask. It
// must be a power of two (1024 x 1024), so texCoords span the whole image (v = 0 is the image
// top) and a texel's mask is at 0.5 + texCoords * 0.5.

in vec3 vertColour;
in vec3 vertNormal;
in vec2 texCoords;

uniform sampler2D Texture;
uniform float Alpha;

uniform vec3 TintColour;

uniform vec3 AmbientColour;
uniform vec3 Light0Direction;
uniform vec3 Light0Colour;
uniform vec3 Light1Direction;
uniform vec3 Light1Colour;
uniform vec3 Light2Direction;
uniform vec3 Light2Colour;
uniform vec3 Light3Direction;
uniform vec3 Light3Colour;
uniform vec3 Light4Direction;
uniform vec3 Light4Colour;
uniform float HueChange;

#include "util/math"
#include "util/hueShift"

// How much of the mask shows unlit: softer than powered, so the two can be told apart.
const float GLOW = 0.45;

void main()
{
	vec3 normal = normalize(vertNormal);

	vec4 texSample = texture2D(Texture, texCoords);
	if(texSample.w < 0.01)
	{
	    discard;
	}

	vec3 col = texSample.xyz;

    float dotprod;
    if(HueChange != 0.0)
    {
        col = hueShift(col, HueChange);
    }

	vec3 lighting = vec3(0.0);

	dotprod = max(dot(normal, normalize(Light0Direction)), 0.0);
	lighting += Light0Colour * dotprod;

	dotprod = max(dot(normal, normalize(Light1Direction)), 0.0);
	lighting += Light1Colour * dotprod;

	dotprod = max(dot(normal, normalize(Light2Direction)), 0.0);
	lighting += Light2Colour * dotprod;

	dotprod = max(dot(normal, normalize(Light3Direction)), 0.0);
	lighting += Light3Colour * dotprod;

	dotprod = max(dot(normal, normalize(Light4Direction)), 0.0);
	lighting += Light4Colour * dotprod;

	lighting += AmbientColour;
	lighting = min(lighting, vec3(1.0));

	vec3 lit = col * TintColour * lighting * vertColour;
	float mask = texture2D(Texture, vec2(0.5) + texCoords * 0.5).r;

	// Masked areas ignore the scene lighting. Tint still applies so the highlight shows.
	col = mix(lit, col * TintColour, mask * GLOW);

    vec4 fragCol = vec4(Alpha * col, Alpha * texSample.w);
	gl_FragColor = fragCol;
}
